#!/usr/bin/env bash

NUMBER_OF_WORKSPACES=5

window_class() {
    echo `hyprctl activewindow -j | jq --raw-output .class`
}

window_title() {
    echo `hyprctl activewindow -j | jq --raw-output .title`
}
activewindow() {
  echo `hyprctl activeworkspace -j | jq --raw-output .id`
}

workspaces (){
    WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')

    ACTIVE_WORKSPACE=$(activewindow)

     seq 1 $NUMBER_OF_WORKSPACES | jq --argjson windows "${WORKSPACE_WINDOWS}" \
       --argjson active "${ACTIVE_WORKSPACE}"\
       --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0) ,active: ($active)})'
}



workspaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do

workspaces
done

