#!/bin/bash

icon1=○
icon2=◎
icon3=●
TOTAL=6
eww="eww -c $HOME/.config/eww"

function handle {
  FOCUSED=$(hyprctl activewindow -j | jq '.workspace.id')
  for((i = 1; i < $TOTAL;i++));
  do
    if [[ $i -eq $FOCUSED ]]; then
      $eww update "wp$i"=$icon3
    else
      $eww update "wp$i"=$icon1
    fi
  done
}
socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | 
  while read line;do handle "$line"; done
